config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :anims
end

app/models/anim.rb
class Anim < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/anims_controller.rb
class AnimsController < ApplicationController
  def index
    @animsIndex = Anim.all
  end

  def new
    @animsNew = Anim.new 
  end

  def create
    @animsCreate = Anim.new(anims_params)

    if @animsCreate.save
      redirect_to anims_path
    else
      render :new
    end
  end

  def show
    @animsShow = Anim.find(params[:id])
  end


  def edit
    @animsEdit = Anim.find(params[:id])
  end

  def update
    @animsUpdate = Anim.find(params[:id])

    if @animsUpdate.update(anims_params)
      redirect_to anims_path
    else
      render :edit
    end
  end

  # def destroy
  #   @animsDestroy = 
  # end

  private

    def anims_params
      params.require(:anim).permit(:name, :gender, :remarks)
    end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/anims_helper.rb
module AnimsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/anims/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @animsEdit do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %><br>
  <br>
  <%= f.label :remarks %><br>
  <%= f.text_area :remarks %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/anims/index.html.erb
<h1>People</h1>
<% @animsIndex.each do |e| %>
  <h2>Name: <%= e.name %></h2>
  <p>Remarks: <%= e.remarks %></p>
  <br>
  <%= link_to 'See Person', anim_path(e) %>
  <br>
  <%= link_to 'Edit Person', edit_anim_path(e) %>
  <br>
  <p><%= link_to 'New Person', new_anim_path %></p>
<% end %>

app/views/anims/new.html.erb
<h1>New Person</h1>
<%= form_for @animsNew do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :gender %><br>
  <%= f.text_field :gender %><br>
  <br>
  <%= f.label :remarks %><br>
  <%= f.text_area :remarks %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/anims/show.html.erb
<h1>Show Individuals</h1>
<h1><%= @animsShow.name %></h1>
<h4><%= @animsShow.gender %></h1>
<p><%= @animsShow.remarks %></p>
<%= link_to 'Back', anims_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Anims', anims_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>